### ISSUE TITLE
Mark record as unfinished

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#106]
It comes from NERC-CEH/irecord-app#44

> I wonder if what we actually need is a way that recorders can flag a record as 'unfinished', and that such a flag would prevent the record being exposed for verification, until such time as the recorder marks it 'finished'?

**Comment by johnvanbreda** [comment]
This exists - occurrence.record_status='I' (in progress) should withold it from reports, verification etc.
