### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#137]
Hi,

I just wonder if we support php7? Since ubuntu 16.04 LTS comes with php7 we should think about this.

I just tired it with our test system - it seems to work generally except:

- there is no php-dbase package in ubuntu, but this was not different before
- I get this error messages in the log: `Uncaught Error: Call to undefined method Error::log_error() in file application/libraries/MY_ORM.php on line 595` and `Uncaught Error: Call to undefined method Error::log_error() in file application/hooks/init.php on line 24`

**Comment by johnvanbreda** [comment]
Hi Daniel
I agree we should support PHP7 in time but it's likely we'll only do that as the need arises. The PHP-Dbase package is optional because it has been excluded from standard builds of PHP for some time now. Therefore it might be that you just need to recompile PHP to support it.
The error log call is our own code so it ought to be easy enough to fix. I wonder if this is a case sensitivity difference and it should actually be error::log_error - can you try this please?

**Comment by japonicus** [comment]
The error::log_error issue is due to a somewhat odd decision in PHP 7 to
define an 'Error' class as part of the php core - a choice of name that
seems absolutely bound to collide with loads of existing code.

http://php.net/manual/en/class.error.php

(Indicia will need to rename it's error class for the sake of PHP7
compatibility)

**Comment by dve** [comment]
@johnvanbreda the call in the code is actually `error::log_error`

I will rename it, and if it works provide a pull request

**Comment by johnvanbreda** [comment]
Thanks for your help @dve.

**Comment by BirenRathod** [comment]
Hello John

Any idea about below error thrown out by PHP 7. you don't see this error if you are on PHP 5.6. This has started from PHP 7.0.12.

indicia/system/libraries/drivers/Session/Cookie.php [69]:

session_regenerate_id(): Session object destruction failed.  ID: user (path: E:\Logfiles\Temp)

Stack Trace

    Indicia::indicia_error_handler( 2, session_regenerate_id(): Session object destruction failed.  ID: user (path: E:\Logfiles\Temp), system\libraries\drivers\Session\Cookie.php, 69 )

    system\libraries\drivers\Session\Cookie.php [69]:

    session_regenerate_id( 1 )

**Comment by johnvanbreda** [comment]
I've not heard of this, but on Googling I found this: https://bugs.php.net/bug.php?id=72156.

**Comment by BirenRathod** [comment]
As I mentioned, this problem only appeared on development warehouse, I got another warehouse using master copy of the Indicia code running on PHP 7 which has not experienced any problem so far.

**Comment by JimBacon** [comment]
The testwarehouse is experiencing this problem. I am unable to login at http://testwarehouse.indicia.org.uk/index.php/login. I will look in to it.

**Comment by BirenRathod** [comment]
That is bit separate problem then this.

**Comment by JimBacon** [comment]
The log shows the following which makes me think it is the same problem.

```
2016-11-14 10:28:55 +00:00 --- error: #2: Error converted to exception. session_regenerate_id(): Session object destruction failed.  ID: user (path: C:\Windows\Temp\) at line 69 in file D:\web sites\testwarehouse\system\libraries\drivers\Session\Cookie.php
2016-11-14 10:28:55 +00:00 --- debug: Stack trace:
	Unknown file - line Unknown - indicia_error_handler
	D:\web sites\testwarehouse\system\libraries\drivers\Session\Cookie.php - line 69 - session_regenerate_id
	D:\web sites\testwarehouse\system\libraries\Session.php - line 239 - regenerate
	D:\web sites\testwarehouse\modules\indicia_auth\libraries\drivers\Auth\ORM.php - line 200 - regenerate
	D:\web sites\testwarehouse\modules\indicia_auth\libraries\drivers\Auth\ORM.php - line 91 - complete_login
	D:\web sites\testwarehouse\modules\indicia_auth\libraries\Auth.php - line 112 - login
	D:\web sites\testwarehouse\application\controllers\login.php - line 54 - login
	Unknown file - line Unknown - index
	D:\web sites\testwarehouse\system\core\Kohana.php - line 291 - invokeArgs
	D:\web sites\testwarehouse\system\core\Event.php - line 209 - instance
	D:\web sites\testwarehouse\system\core\Bootstrap.php - line 55 - run
	D:\web sites\testwarehouse\index.php - line 112 - require

2016-11-14 10:28:55 +00:00 --- error: Uncaught ErrorException: session_regenerate_id(): Session object destruction failed.  ID: user (path: C:\Windows\Temp\) in file D:/web sites/testwarehouse/system/libraries/drivers/Session/Cookie.php on line 69

```

**Comment by BirenRathod** [comment]
Also, I found warehouse is not up to date with latest code.
