### ISSUE TITLE
Email check is case sensitive

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#151]
The warehouse should not allow two users to be created with the same email address. A check is performed but is case sensitive which it should not be. I.e. if there is a user, a@example.com, you can create another with email A@example.com.

**Comment by JimBacon** [comment]
A query, 
```
SELECT lower(p.email_address) email, count(*)
FROM people p
GROUP BY lower(p.email_address)
HAVING count(*) > 1
ORDER BY count(*) desc, lower(email_address)
```
shows there are 744 people on warehouse1 affected by this and they continue to be created.

**Comment by johnvanbreda** [comment]
Fixed. See https://github.com/Indicia-Team/warehouse/commit/bf10670a010aba21b0295a7cea2f9167c1048941
