### ISSUE TITLE
Inconsitend beahvior updateing entity with additional attributs

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#183]
When updating an entity, eg. a survey, via the data service with additional attributes on which ```Allow Multiple Values``` is set to true there is an inconsistent behavior handling them.

If you send tow instances first like:
```
srvAttr:47::0 = "ABC"
srvAttr:47::1 = "DEF"
```

The survey has the attribute 47 with "ABC" and "DEF" as value.

If you now update the survey with these additional attributes:
```
srvAttr:47::0 = "GHI"
```
Then the tow ones from the first request get deleted and the survey now only has "GHI" as an value for attribute 47. If you want to keep the old values you have to add them like
```
srvAttr:47:1234 = "ABC"
srvAttr:47:1235 = "DEF"
```

That's all fine, but if you want to delete all of them, and sending a request without ```srvAttr``` then the last state is still there.

According to the beauvoir I think then all existing values should get deleted.

**Comment by johnvanbreda** [comment]
I'm a bit nervous of this as it affects what happens when you resubmit a record partially, e.g. you might want to update just the date of a record and leave other values intact. 
What happens if you submit srvAttr:47="" to try to null out the whole value?

**Comment by dve** [comment]
You don't have to be nervous since your tip worked. I've created a pull request for the documentation.
