### ISSUE TITLE
Request for easier display of parent/child relationships in samples/locations on warehouse

### ISSUE THREAD

**Issue by Gary-van-Breda** [Indicia-Team/warehouse#185]
Would it be possible to get extra tabs added on the warehouse sample and location detail pages which display any children they have, and also a link to any parent it has?

**Comment by johnvanbreda** [comment]
Hi Gary, you probably need to ask @DavidRoy if or when I should prioritise this, or can you add them yourself?

**Comment by Gary-van-Breda** [comment]
David: do you have any feelings on this? It would make navigating samples and locations on the warehouse much easier for many projects, including UKBMS. Technically I can do it, but its a case of getting go-ahead.

**Comment by DavidRoy** [comment]
Yes, I agree this is useful so please go ahead.

**Comment by Gary-van-Breda** [comment]
Code lodged into dev and a pull setup for master, targeting 1_32_0

**Comment by johnvanbreda** [comment]
Now live.
