### ISSUE TITLE
Problem retriving custom sample attributes by a report

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#221]
The report-api is not delivering custom sample attributes, if the attribute is used as a "non survey specific" attribute, because of a check on ```sample_attributes_websites.restrict_to_survey_id```.

This can be checked with ```library/samples/samples_list_2``` report from within the warehouse. If e.g. the weather attribute (id 1) is not associated directly with a survey its not delivered, even if "MyWebsite: non survey specific" is selected. If one associates it with a concrete survey it gets delivered.

**Comment by johnvanbreda** [comment]
Fixed in develop branch so will get included in the next feature release.
