### ISSUE TITLE
Live warehouse tabs not loading

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#222]
There is a problem with the live warehouse. For example, try loading the Taxa tab on a species list,
the following error will occur,

"TypeError: $.cookie is not a function"

It is possible to force tabs to load by double-clicking on them, but the javascript error still causes functionality on the page to fail such as Add Species To Child List

**Comment by johnvanbreda** [comment]
Are you sure this happens on the current release? It was a bug until a few weeks ago - see https://github.com/Indicia-Team/client_helpers/commit/4eedbe8a79a28c20256818fa3e34e217e55da3ca for the fix.

**Comment by andrewvanbreda** [comment]
It is on the live warehouse, I saw it earlier today and yesterday. Biren saw it to. I did just try now though and it did work fine. So I will look again tomorrow for you. It was definitely broken earlier.

**Comment by johnvanbreda** [comment]
Is it possible you just needed to refresh the browser cache (Ctrl-R)?

**Comment by andrewvanbreda** [comment]
Um....don't know. I did try several browsers and had the issue. Biren saw it as well. It seems to have been working since last night though. If you are happy with this feel free to close this.
