### ISSUE TITLE
Species Alerts sent for training records

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#225]
Should species alerts be sent for training records?, currently they are and don't indicate they are training records.

My guess is these should be optional, off by default (optional for testing purposes), with an indication that it is a training record in the email if that is possible. If you can confirm I can patch it.

**Comment by johnvanbreda** [comment]
@andrewvanbreda I agree with your proposal.

**Comment by andrewvanbreda** [comment]
This was fixed quite a while ago and has been seen to be working in tests
