### ISSUE TITLE
Error message on warehouse, new milestone setup milestone

### ISSUE THREAD

**Issue by DavidRoy** [Indicia-Team/warehouse#238]
http://warehouse1.indicia.org.uk/index.php/milestone/create/?

Throws up an error message:
Error occurred when loading page.
Undefined index: website_id
For more information refer to the application log file.

**Comment by johnvanbreda** [comment]
The link to create a milestone should be followed from the tab of milestones on the edit page for a website. If you do this then the website ID is included in the link and it works, e.g. http://warehouse1.indicia.org.uk/index.php/milestone/create/23. 
@DavidRoy how did you get that link?

**Comment by DavidRoy** [comment]
I think I had this link from previous email threads.  Thanks for resolving - now closing

**Comment by kitenetter** [comment]
Oli and I have just set up a new milestone on iRecord for bryophyte recorders who add 100 records, and have a couple of questions for @johnvanbreda : 

1. Do the milestone notifications get applied retrospectively (i.e. will everyone who has already added 100 records to iRecord get a notification), or does it only apply to people reaching the 100 record milestone from this point onwards?
2. How do users receive the milestone message, is it via the usual notification process, and will therefore depend on the notification settings in their profile?
