### ISSUE TITLE
Filter missing on People and Users

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#242]
Between v1.30.3 (testwarehouse) and 1.30.5 (warehouse1) the people and user pages have lost the filter to allow searching of records.

**Comment by johnvanbreda** [comment]
There should be a filter row at the top of the grid. I had to change this to a report based grid because the way the grid worked before it created filter URLS that were too long (unless you were logged in as admin with no filter).

**Comment by JimBacon** [comment]
Quite right. I didn't see that. Perhaps, by degrees, we can standardise on that to maintain a consistent interface.
