### ISSUE TITLE
Warehouse needs php mysql module to be loaded

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#248]
At least the setup routine fails with
```
2017-06-12 12:49:21 +02:00 --- error: Uncaught Error: Call to undefined function mysqli_connect() in file system/libraries/drivers/Database/Mysql.php on line 61
```

If `php-mysql` is not installed - since indicia does not use mysql this should not be the case

**Comment by johnvanbreda** [comment]
Have you tried clearing your cookies? I suspect your browser still thinks it is logged in to a previous warehouse instance from the same location.

**Comment by dve** [comment]
Hi John,

cleaning cookies did it
