### ISSUE TITLE
Improve distinction between warehouses

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#251]
We have Live, Test, Dev warehouses which have different roles but are easily confused when more than one is open in a browser. Providing a strong visual indication would be useful. In addition, if running code from a branch other than master, it would be helpful to signpost that too.  At present there is a config setting called warehouse_title in the indicia.php config which helps if set but is a little inconspicuous.

Arising from https://github.com/BiologicalRecordsCentre/BSBI-Card-and-PlantPortal/issues/47

**Comment by BirenRathod** [comment]
Any idea @johnvanbreda ? why 'dev' on devwarehouse doesn't display on the browser?

**Comment by JimBacon** [comment]
The config setting is still 'Indicia Warehouse' in application\config\indicia.php I think.

**Comment by BirenRathod** [comment]
That is the same for warehouse2.indicia.org.uk, but it displays 'dev' instead.

**Comment by JimBacon** [comment]
warehouse2 is putting (dev) in the footer, perhaps from the version number. I don't have access to that server to check. The setting John is talking about would change the title which would appear on the browser tab I think.

**Comment by BirenRathod** [comment]
All warehouses have got same settings, but only one warehouse has picked up the 'dev' value. Is there anywhere else I could find the value for this upgrade.continuous_upgrade variable value set?  I couldn't find on live warehouse or dev warehouse.

**Comment by JimBacon** [comment]
Oh yes, I see from application\views\templates\template.php that (dev) is appended if continuous upgrade is enabled. That checks and runs new database scripts on each page load and is set in modules\indicia_setup\config\upgrade.php. Unless actively developing database scripts that is probably best kept off.

**Comment by BirenRathod** [comment]
Yes, that is for database scripts.
So, that means we need a distinction for all these warehouses to identify with their branch.

**Comment by johnvanbreda** [comment]
I've just pushed a change in the develop branch which shows the warehouse title configuration in the footer as well as including it in the head title element.

I would actually propose we strip out the continuous upgrade feature - it is rarely used, of dubious benefit and I am always keen to reduce complexity where possible.
