### ISSUE TITLE
Error trying to edit term which uses a termlist_term_attribute on dev warehouse code

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#252]
There seems to be a bug in the dev warehouse where if you click to edit a term and that term uses a termlsit_term_attribute an error occurs.
Try this page
http://devwarehouse.indicia.org.uk/index.php/termlist/edit/651

Although note it doesn't seem to happen with all the terms.

D:/web sites/indiciadev/application/controllers/gridview_base.php [166]:
Undefined index: termlists_term_attribute_id
Stack Trace

application\controllers\gridview_base.php [166]:
Indicia::indicia_error_handler( 8, Undefined index: termlists_term_attribute_id, application\controllers\gridview_base.php, 166, Array

see message on screen for full details

**Comment by BirenRathod** [comment]
Do you still see this error? I can't.

**Comment by andrewvanbreda** [comment]
Yes I do, try editing the top one in the list, alternatively I think going directly to the link here will throw the error
http://devwarehouse.indicia.org.uk/index.php/termlists_term/edit/10777

**Comment by johnvanbreda** [comment]
There was an incorrect fieldname in the list_termlists_term_attribute_values view. I've fixed it but the dev server will need to be upgraded.

**Comment by BirenRathod** [comment]
For that, I need to switch it to develop branch. @andrewvanbreda, are you ok, if I switch feature-plant-portal-importer-may-build to develop branch?

**Comment by johnvanbreda** [comment]
Or perhaps better, you can merge the develop branch into your feature branch.

**Comment by BirenRathod** [comment]
What will happen if @andrewvanbreda will stop using feature-plant-portal-importer-may-build and delete?
will develop branch still remain with all changes?

**Comment by andrewvanbreda** [comment]
No, the develop branch doesn't have the changes because I think we decided before that for it to be in the develop branch it would need to be in a releasable state. I will merge the develop branch into he feature branch, there are actually two branches with the same name for plant portal (one client helpers, one warehouse). The client helpers merged fine, but I got conflicts on the warehouse, I will fix that first thing tomorrow and let you know

**Comment by andrewvanbreda** [comment]
I have failed to get this to work. @BirenRathod I am getting a problem in source tree where it is complaining about conflicts in the client_helpers and media folders when I merge the warehouse, but this merge doesn't relate to Media at all. I don't understand that, isn't the warehouse  merge independent of those folders. If you try to discard those hunks it even ignores me and says nothing at all.
Any ideas? I have tried switching the client_helpers folder to the feature-plant-portal-importer-may-build-branch (which was already merged successfully yesterday) and merging again and it still fails even though one of the warnings I saw was to try to merge that folder (see second screenshot)



![conflict](https://user-images.githubusercontent.com/2463614/28263270-04c42c1a-6ade-11e7-8a3e-205a4bab33ca.jpg)
![conflict message 2](https://user-images.githubusercontent.com/2463614/28263278-0a1e1c2a-6ade-11e7-8e57-d45503999280.jpg)

**Comment by BirenRathod** [comment]
Hello @andrewvanbreda 
This could occurred if there are some changes in the queue are pending to pull not from you but somebody else. I only suggest that before you merge please fetch code in both branches and try to merge.

**Comment by andrewvanbreda** [comment]
Hi Biren, 

I think I tried that but perhaps I am wrong, I will try again in the next hour or so and I will let you know if I have any success

**Comment by johnvanbreda** [comment]
If you've not made any changes to the media and client_helpers folders intentionally then you can reset them to the original version - from the command line:
```
git reset --hard origin/client_helpers
git reset --hard origin/media
```
I don't know the source tree equivalent, presumably you can look it up.

**Comment by BirenRathod** [comment]
Yes, that is good idea. @andrewvanbreda , you could use terminal to run this command and source tree will refreshed automatically.

**Comment by andrewvanbreda** [comment]
Still getting conflicts, tried pulling from every branch first including dev/master/my feature, in client_helpers and media :( Will have to think again

**Comment by andrewvanbreda** [comment]
I still don't understand at all as media as nothing to do with this

**Comment by andrewvanbreda** [comment]
Ok, not tried the terminal thing yet, I will give that a go

**Comment by andrewvanbreda** [comment]
I got the commands to run (although I had to actually navigate to the folder, other people online also have a problem running this with a path). Unfortunately this didn't help, if you have any other ideas let me know, else I will just have to try and fix it...somehow

**Comment by andrewvanbreda** [comment]
Note the messages I am receiving are the same as before, it isn't a different message

**Comment by BirenRathod** [comment]
@andrewvanbreda , last thing you could try is delete the respository on your local machine and clone again. This way you can delete the git history. No risk of loosing anything just bit more work.

**Comment by andrewvanbreda** [comment]
@BirenRathod that is a good idea, but unfortunately I have already tried that previously several times. I might have to think about deleting and recreating that feature branch which is my usual course of action when Github is in a tangle.

**Comment by BirenRathod** [comment]
Could be one of the drawback of GitHub.

**Comment by andrewvanbreda** [comment]
John has worked me through the tangle. This should now all be ready for you to do whatever you wanted with it. Note that the feature-plant-portal-importer-may-build was previously included in the code to appear on the warehouse footer. John says he has changed the code to now allow this to be placed into the warehouse config file, so if you want the branch name to display you will need to change the config file
