### ISSUE TITLE
Unexpected viewing of deleted records.

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#257]
Having deleted a sample using the warehouse website, e.g. http://warehouse1.indicia.org.uk/index.php/sample/edit/2552642, it remains viewable as does its occurrence which was also marked deleted by the operation, http://warehouse1.indicia.org.uk/index.php/occurrence/edit/5097778. However, all the attribute information is removed from those views.

My expectation was that deleted records would not be viewable. If they are to be viewable I would expect, as a matter of consistency, that their attribute information would also be presented. Moreover, if they are to be viewable, an indication that you are looking at a deleted record might be useful.

Far from a priority but thought I'd log it.

**Comment by johnvanbreda** [comment]
Tested in current develop branch and no longer a problem so closing.
