### ISSUE TITLE
Non-coreAdmin unable to edit people

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#259]
If a website admin (who is not a core admin) attempts to edit a person an exception occurs.
The log contains the following
```
--- error: #2: Error converted to exception. in_array() expects parameter 2 to be array, integer given at line 132 in file E:\git\warehouse\application\controllers\person.php
--- debug: Stack trace:
	Unknown file - line Unknown - indicia_error_handler
	E:\git\warehouse\application\controllers\person.php - line 132 - in_array
	E:\git\warehouse\application\controllers\indicia.php - line 171 - record_authorised
	Unknown file - line Unknown - edit
	E:\git\warehouse\system\core\Kohana.php - line 291 - invokeArgs
	E:\git\warehouse\system\core\Event.php - line 209 - instance
	E:\git\warehouse\system\core\Bootstrap.php - line 55 - run
	E:\git\warehouse\index.php - line 112 - require

```

**Comment by johnvanbreda** [comment]
I've got a hotfix ready to commit which fixes this error message, but I'd like to take the opportunity to check up on how permissions should be handled. At the moment a non core-admin can only edit their own person record. There are 3 other categories of person record:
1) People linked to a user account associated with a single website.
2) People linked to a user account associated with multiple websites.
3) People linked to no user account at all.
The question of these is which should be editable for a non core-admin?

**Comment by Gary-van-Breda** [comment]
I think it should depend on the the site role the editing user has on the website:
1) Yes, if the editing user has an admin site role on that website.
2) Yes, if the editing user has an admin site role on **all** those websites. If this is not possible, then 'No'.
3) No.

**Comment by JimBacon** [comment]
In my experience, the task that Website Admins have to perform via the warehouse interface is the management of users who need to be given Editor or Admin role on the website. If the person does not already exist then they have to create the person. If they make a mistake they might want to edit that person. That suggests an alternative approach to permissions might be that they can continue to edit the person while they match the updated_by_id. 

The issue was actually more about an unhandled exception rather than permissions. My expectation was that the Website Admin would be able to edit people but this may not be a requirement. This issue was not encountered because someone wanted to edit a person but because they could not find the person in the list of users, as described in #258.

**Comment by johnvanbreda** [comment]
Thanks both. I think Gary's suggestion seems logical and allows a website admin to edit person records for users who registered via the website. Jim - it was in fixing the exception that I noticed the behaviour as coded meant that a website admin could only edit their OWN person record, not any of the associated people linked to their website. This seems wrong, hence the question.

**Comment by JimBacon** [comment]
I take your point though it doesn't appear to have caused any particular problem over the last few years so I would give it a low priority if it is any significant effort.

**Comment by johnvanbreda** [comment]
Agreed. I'll prioritise the fixes required to ensure that site admins can follow the workflow you described regarding being able to add a person then create a user account with admin privileges to their website.
Looking at the code though I can make the permissions for editing a person the same as the existing permissions for editing a user (since that already checks the person ID) with very little effort.

**Comment by johnvanbreda** [comment]
Permissions for editing a person now use the same code as permissions for editing a user.
