### ISSUE TITLE
Multiple website agreements not honoured

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#262]
Let two websites, A & B, both join two agreements X & Y.

The view, build_index_websites_website_agreements, will end up with 4 rows to represent this information:
A -> B :  agreement X
A -> B :  agreement Y
B -> A :  agreement X
B -> A :  agreement Y

When the index_websites_website_agreements is updated by the database function, refresh_index_websites_website_agreements(), there is no provision made to combine the agreements in to single definitions of the sharing from A->B and B->A. Instead the result is unpredictable.

**Comment by johnvanbreda** [comment]
Fixing this as working on other changes to agreements relating to allowing editing records from other websites. Will be done in the next feature release.
