### ISSUE TITLE
Oddities in submission response

### ISSUE THREAD

**Issue by Gary-van-Breda** [Indicia-Team/warehouse#264]
Whilst investigating a UKBMS issue; I noticed that the response to a submission (through the ajaxproxy) was inconsistent:

In the initial save, the model id is returned as a string, subsequent saves as an integer.

In the initial save, the created_on date is in the format Ymd H:mi:s
On subsequent saves the created_on date is in the format Y-m-d H:mi:s 
The updated_on stays as format Ymd H:mi:s

In addition there is one case where the created by date on non-initial saves on an submodel is stating 2016-06-25 21:20:28 when it was created today (occurrence id 5653043; attribute value 7313772)

**Comment by Gary-van-Breda** [comment]
If what I'm seeing is correct then the allocation of an ID to the attribute value is wrong, and is reusing existing IDs: this may be corrupting existing data.
E.G. the attribute value given above was created in 2016!

**Comment by Gary-van-Breda** [comment]
Further investigation: the initial attribute was saved into a value record with an ID of 11555778; but the submission return value specified an id of 7355393; which was then used for a later submission.

**Comment by Gary-van-Breda** [comment]
I believe that there is an issue with the auditing module.
The *_comment, *_attribute_value and *_media (where * is occurrence, sample or location), and location_websites all insert audit records when an insert is done. This is done immediately after the INSERT on the actual record. The audit insert includes a NEXTVAL on the audit sequence; but this is before the main record calls LASTVAL to fetch the ID of the record: thus the ID in the saved record model is pointing to the ID of the audit record, not itself.
This is then passed back as part of the submission response. If the calling form then uses this incorrect ID it will lead to data corruption in the warehouse (e.g. saving changed attribute data in the wrong attribute value record). This is happening with UKBMS.
It only affects INSERTs into these records as that is when the LASTVAL is used to populate the model ID, otherwise it comes from the record itself.
I think we need to at the very least switch off the auditing of the INSERTs on these tables.  
@johnvanbreda : can you do this? Is this acceptable as a temporary measure until we fix this?

**Comment by johnvanbreda** [comment]
I've disabled the insert triggers using the attached script. Will you pick up the issue with the audit module?
[disable insert audit triggers.txt](https://github.com/Indicia-Team/warehouse/files/1254664/disable.insert.audit.triggers.txt)

**Comment by Gary-van-Breda** [comment]
See pull request #265

**Comment by Gary-van-Breda** [comment]
After the code is put in and the INSERT triggers restarted, I'll need a download of the warehouse so I can work on figuring out the extent of any data corruption.

**Comment by johnvanbreda** [comment]
The pull request has been merged (with a small change for postgreSQL < v9.5 compatibility) and the insert triggers reinstated.
@BirenRathod or @JimBacon can you help Gary with the backup or data access via some other method?

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon : are you able to give me a backup from warehouse1? I think I primarily need the audit schema.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 
As requested, the audit schema, you could download it from this link : https://www.dropbox.com/s/9v1s991astg192i/Audit.zip?dl=0

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon : can you run the following SQL script against the database? This is a small excerpt of the file that will be run, which I have tested on my version of the warehouse database, but I want to check it works OK on the real thing first with a small sample.
[audit_fix_1.zip](https://github.com/Indicia-Team/warehouse/files/1314724/audit_fix_1.zip)

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 

I have updated those record by running query from above zip file.

Here is the result. 
[Audit_Query_result.txt](https://github.com/Indicia-Team/warehouse/files/1324428/Audit_Query_result.txt)

Biren

**Comment by Gary-van-Breda** [comment]
Thanks @BirenRathod.
This is the full change: 
[audit_fix_full.zip](https://github.com/Indicia-Team/warehouse/files/1344354/audit_fix_full.zip)
Can you run this against the warehouse1 database?
Thanks

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 

It has updated all records from the sql.

**Comment by JimBacon** [comment]
The fault in the audit module, fixed in response to this issue, caused other corruption in the database, noticed at a later date, which needed repairing. @Gary-van-Breda  wrote by email:

> The underlying auditing problem was fixed by #264, hence the reason it stops on 27 Aug. However it was the interaction of the auditing with another (up to now benign) feature in the attribute value processing, whereby a double save is carried out, that caused the issue.
> Notes:
> - All of the instances involve *_attribute_values
> - There are gaps in the audit id sequence where there are no corrupting attribute updates after the insert of the*_attribute_values . This is caused by the double save not saving any changes to the record.
> - Whether the record is corrupted and which field was determined by the attribute type, relative to the record just saved.
> - All the corruptions involved purely setting the text_value, the float_value or the int_value fields to null; no other data was changed in the row and not to any other values, not even the updated_by/on fields, and certainly not the parent record it is attached to – which was the case in the other previous bug’s symptoms.
> - All the corruptions save the previous value in the audit table, so it is recoverable.
> - 27/8/2017 was when we shut down the auditing before putting in the updated audit module.

 The following script was used to perform the repair.
```
CREATE OR REPLACE FUNCTION fix_audit2() RETURNS integer AS $$
DECLARE
  auditrecord audit.logged_actions%ROWTYPE;
  curaudit refcursor;
  rowaudit audit.logged_actions%ROWTYPE;
  processed integer := 0;
  value text;
  changed_column text;
  query text;
BEGIN
  --- L1 holds the audit record of the insert: the ID of the audit record was incorrectly handed back as the primary key
  --- L2 holds the bad update to the wrong OAV
  --- There seem to be no triple duplicates - makes life easier
  FOR auditrecord IN SELECT l2.* FROM audit.logged_actions l1
      JOIN audit.logged_actions l2 ON l2.action = 'U'
          AND l2.transaction_id = l1.transaction_id and l2.event_record_id = l1.id
      WHERE l1.action = 'I'
      AND l1.id < l2.id --- bad update must be after the INSERT
      order by l2.id
  LOOP
    RAISE INFO '--- audit rebuild : Looking at audit ID % : AttrValID %', auditrecord.id, auditrecord.event_record_id;
--- If not an attribute_value, raise an exception
    IF auditrecord.event_table_name NOT LIKE '%_attribute_values'
    THEN
            RAISE EXCEPTION 'audit rebuild : Table type mismatch [%]', auditrecord.event_table_name;
    END IF;
--- Read in all the attribute value updates of the orignal l2, to see if any changed later - if so do nothing.
    OPEN curaudit FOR SELECT * FROM audit.logged_actions l3
      WHERE l3.event_record_id = auditrecord.event_record_id
        AND auditrecord.id < l3.id
        AND l3.event_table_name = auditrecord.event_table_name ;
    FETCH curaudit INTO rowaudit;
    IF FOUND THEN
      RAISE INFO '--- audit rebuild : AttrValID ID % updated in audit record % : ', auditrecord.event_record_id, rowaudit.id;
    ELSE
      changed_column = '';
      value= '';
      IF array_length(akeys(auditrecord.changed_fields), 1) <> 1 THEN
            RAISE EXCEPTION 'audit rebuild : number of changed fields not equal to 1';
      END IF;
      IF auditrecord.changed_fields ? 'int_value' then
        changed_column = 'int_value';
        value = auditrecord.row_data->'int_value';
        IF (auditrecord.changed_fields->'int_value') IS NOT NULL
        THEN
              RAISE EXCEPTION 'audit rebuild : INT_VALUE changed to not null value';
        END IF;
      ELSE
      IF auditrecord.changed_fields ? 'float_value' then
        changed_column = 'float_value';
        value = auditrecord.row_data->'float_value';
        IF (auditrecord.changed_fields->'float_value') IS NOT NULL
        THEN
              RAISE EXCEPTION 'audit rebuild : float_VALUE changed to not null value';
        END IF;
     ELSE
     IF auditrecord.changed_fields ? 'text_value' then
        changed_column = 'text_value';
        value := auditrecord.row_data->'text_value';
        IF (auditrecord.changed_fields->'text_value') IS NOT NULL
        THEN
              RAISE EXCEPTION 'audit rebuild : text_value changed to not null value';
        END IF;
     ELSE
              RAISE EXCEPTION 'audit rebuild : missing field';
     END IF;
     END IF;
     END IF;
      IF value <> '' THEN
        query = format('UPDATE indicia.%I SET %I=%L, updated_on=now(), updated_by_id=1 WHERE id = %s;',
              auditrecord.event_table_name,
              changed_column, value,
              auditrecord.event_record_id);
        Raise INFO '%', query;
--        EXECUTE query;

          processed := processed +1;
      END IF;
    END IF;
    CLOSE curaudit;
  END LOOP;
  RAISE INFO '--- % processed', processed;
  return processed;
END 
$$ LANGUAGE plpgsql;

SELECt fix_audit2();

```

**Comment by JimBacon** [comment]
Following the application of the second fix it was found that some attribute values were still null. This arose because they had been doubly corrupted. Looking at an example attribute by way of explanation.
Created as
```
id => 5217388,
int_value => NULL,
text_value => 9,
updated_on => 2015-09-15 22:03:06,
occurrence_id => 2485905,
occurrence_attribute_id => 447
```
Corrupted by the second mechanism, setting text_value to null, yielded
```
id => 5217388,
int_value => NULL,
text_value => NULL,
updated_on => 2015-09-15 22:03:06,
occurrence_id => 2485905,
occurrence_attribute_id => 447
```
Corrupted by the first mechanism, completely altering state, yielded
```
id => 5217388,
int_value => 12,
text_value => NULL,
updated_on => 2017-07-24 15:47:25,
occurrence_id => 5430986,
occurrence_attribute_id => 3
```
The first fix restored the attribute to the middle state. The second fix was skipped as the record was recognised as updated, assumed to be by the user, and therefore not altered leaving it null. Having a list of all attributes not updated by the second fix it was possible to repeat the second fix on all attributes that had been skipped and still had a null value.

**Comment by Gary-van-Breda** [comment]
@JimBacon Is there anything you need me to do at this point?

**Comment by JimBacon** [comment]
No thanks @Gary-van-Breda , I was just documenting another aspect of this problem and the steps I took to restore data.
