### ISSUE TITLE
location shapefile upload error

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/warehouse#271]
I have admin rights for the Merseyside BioBank website which uses the BRC/CEH warehouse. Using my login i am trying to upload a shapefile containing a boundary for a location i would like to be able to report on. The shapefile has been checked for data errors, simplified (thinned) and is a relatively small site. It is projected in ESPG:27700 and opens fine in Mapinfo and QGIS.

All attributes with the exception of the location name have been removed. The location name field is stored as a string.

I have followed the instructions as per [the doc](https://media.readthedocs.org/pdf/indicia-docs/latest/indicia-docs.pdf) page 225. The shapefile is attached as are screen shots of the upload, error response and log errors from the warehouse pointing to line 292 of locations.php (the linked function).

From what i can see there appears to be a problem accessing the .dbf despite it having already been read to allow me to select the location name attribute?

[Childwall_Woods.zip](https://github.com/Indicia-Team/warehouse/files/1333394/Childwall_Woods.zip)
![upload error](https://user-images.githubusercontent.com/7861877/30863803-dc0beffa-a2c9-11e7-8c33-be09640ad3c0.png)
![location settings](https://user-images.githubusercontent.com/7861877/30863801-dbf09ade-a2c9-11e7-8557-aff17d52a749.png)
![location upload page](https://user-images.githubusercontent.com/7861877/30863802-dbf8be26-a2c9-11e7-9a1d-c4ce3ddff5b6.png)
![warehouse error log](https://user-images.githubusercontent.com/7861877/30863805-dc19f8f2-a2c9-11e7-932e-5e2ed651327a.png)

https://github.com/Indicia-Team/warehouse/blob/26e835ffcb90ca05fa24e4f5f738307b6250c341/application/controllers/location.php#L292

**Comment by JimBacon** [comment]
I can add another piece of information from examining the files on the server.

The program is trying to open D:\web sites\warehouse1\extract\Childwall_Woods_LWS.dbf
This does not exist so the error is not surprising.
The file is actually in a subfolder of the extract directory, specifically D:\web sites\warehouse1\extract\Childwall_Woods\Childwall_Woods_LWS.dbf

**Comment by JimBacon** [comment]
On looking at your zip file, I see it contains a folder.
I.e. you have
```
Childwall_Woods.zip
| 
|__Childwall_Woods
  |
  |__Childwall_Woods_LWS.dbf
```
That is not what that doc asks for. 
Try simply
```
Childwall_Woods.zip
| 
|__Childwall_Woods_LWS.dbf
```

**Comment by benj-d** [comment]
Works as designed.
