### ISSUE TITLE
Scheduled tasks not running on warehouse1

### ISSUE THREAD

**Issue by Gary-van-Breda** [Indicia-Team/warehouse#273]
It looks like the last successful run was on 29th Sept at 11:30.

**Comment by johnvanbreda** [comment]
I'll take a look

**Comment by BirenRathod** [comment]
Seems like it has stopped after I enabled and didn't stay on.

**Comment by BirenRathod** [comment]
I did that after I upgraded the PHP.

**Comment by johnvanbreda** [comment]
Biren - don't do anything - I've started a manual run through, and will make sure it is re-enabled properly at the end.

**Comment by BirenRathod** [comment]
No, I'm not. Yes, I noticed that. thanks.

**Comment by BirenRathod** [comment]
Seems like it didn't re-enable. I have restarted.

**Comment by BirenRathod** [comment]
It is now running fine.
