### ISSUE TITLE
Species not really deleted from species lists

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#280]
I have noticed a problem where it seems (that at least often) if you delete a species from a species list it isn't really deleted.
I have noticed two symptoms of this

1. If I remove a species from a list that is used for species alerts, the user continues to receive alerts even though the Warehouse UI is showing that the species isn't there.

2. If you have a child species list, and you try to use the "Add" button to re-add a species from the parent list, after the species has previously been on the child list and removed, then you will be told you can't because the species is already present. Even though it can't be seen in the list.
Strangely using "Add many" and just adding the one item does seem to allow it to be added.

Am using species list 230 "NI Invasive Red Alert List - Senior Wildlife Officer".
Chinese Muntjac was removed from the list but seems to still be present in the cache_taxa_taxon_list table, and I don't think its delete flag is set on the taxa_taxon_list table either (so actually I am not actually sure how the Warehouse UK knows not to show it)

Am pretty sure this problem isn't a one off, I have seen it before, but I didn't realise the extent of the issue until I saw it was causing alert problems

**Comment by andrewvanbreda** [comment]
@BirenRathod Are you able to assist with this issue?
There is definitely an issue here as I have now checked and it fails on my own box. It is occurring if you have a child species list, and that list has a species that is inherited from the parent list, then if you delete that species from the child list it is left in the cache_taxa_taxon_list table.
Could you run this sql please.

select id,taxon_list_id from indicia.cache_taxa_taxon_lists where id in
(select id from indicia.taxa_taxon_lists where deleted=true)
order by taxon_list_id

We actually have 2 issues here, I can try to patch the code, but I don't think that would clean up the existing data. If you run the above, we can try to get an idea of the extent of the issue, thanks

Cheers for any help you can provide

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Yes, no problem.

The query has got no result.

**Comment by andrewvanbreda** [comment]
Bug fixed in add_single_taxon_from_parent_list and committed to develop.
Stil unclear whether there is an issue with cache table

**Comment by andrewvanbreda** [comment]
Working now on live. Unclear if their was ever an issue with cache tables, so closing now. Will open new issue if anything crops up in the future.
The user who originally reported the species alert problem has not had the issue recently and will let me know if they see it again. This can't be related to the species list delete problem, so can be raised separately if it appears again in the future, although code inspection doesn't indicate any obvious problem.
