### ISSUE TITLE
Automated tests failing

### ISSUE THREAD

**Issue by Gary-van-Breda** [Indicia-Team/warehouse#289]
It looks like there are hardcoded years in the vague date automated expected test values for things like "Autumn": these are currently showing 2017, but the return values are now 2018.

**Comment by JimBacon** [comment]
Yes, in https://github.com/Indicia-Team/warehouse/blob/master/application/tests/helpers/vague_dateTest.php there is a comment 

> Month only and season only years are always for the current year so will need updating with time.
