### ISSUE TITLE
PHP error generated by subscription_settings.php

### ISSUE THREAD

**Issue by BirenRathod** [Indicia-Team/warehouse#292]
Below are two examples of error generated by subscription_settings.php

[01-Mar-2018 12:00:53 Europe/Dublin] PHP Fatal error:  Uncaught Exception: 6 - Could not resolve host: warehouse1.indicia.org.uk\ in D:\web sites\warehouse1\subscription_settings.php:194
Stack trace:
#0 D:\web sites\warehouse1\subscription_settings.php(163): subscription_settings::http_post('warehouse1.indi...', 'website_id=-703...')
#1 D:\web sites\warehouse1\subscription_settings.php(81): subscription_settings::getAuth(-70356, 'Indicia')
#2 D:\web sites\warehouse1\subscription_settings.php(48): subscription_settings::notificationEmailSettings()
#3 {main}
  thrown in D:\web sites\warehouse1\subscription_settings.php on line 194

[04-Mar-2018 16:16:10 Europe/Dublin] PHP Fatal error:  Uncaught Exception: 6 - Could not resolve host: warehouse1.indicia.org.uk\ in D:\web sites\warehouse1\subscription_settings.php:194
Stack trace:
#0 D:\web sites\warehouse1\subscription_settings.php(163): subscription_settings::http_post('warehouse1.indi...', 'website_id=-148...')
#1 D:\web sites\warehouse1\subscription_settings.php(81): subscription_settings::getAuth(-148235, 'Indicia')
#2 D:\web sites\warehouse1\subscription_settings.php(48): subscription_settings::notificationEmailSettings()
#3 {main}
  thrown in D:\web sites\warehouse1\subscription_settings.php on line 194

**Comment by BirenRathod** [comment]
This happens regularly.

**Comment by johnvanbreda** [comment]
Should now be fixed. See https://github.com/Indicia-Team/warehouse/commit/728ad17c19a95614c8812381b3affd85ee446236
