### ISSUE TITLE
Linking to Warehouse during registration still too slow

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#293]
I think this was improved about 6 months ago, but the linking of a Drupal user account to the Warehouse is too slow. I think it improved, but these days it seems to be in the region of 10 seconds which is enough for some users to think browser has hung.

Tested on NPMS. Will see what iRecord does.

**Comment by andrewvanbreda** [comment]
iRecord seemed better at 6/7 seconds. AVB to check NPMS again.

**Comment by andrewvanbreda** [comment]
NPMS behaviour is the same as iRecord today at 6/7 seconds. NPMS 10 seconds yesterday.
Conclusion is this varies somewhat and is not acceptable speed when at its worst.
Thoughts @johnvanbreda 
I know last time this was improved you managed to remove some old redundant code.

**Comment by johnvanbreda** [comment]
Fixed, some more query optimisations in the get_user_id webservice.
