### ISSUE TITLE
indiciaData is not defined

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#294]
When opening some of the warehouse [website pages](https://warehouse1.indicia.org.uk/index.php/survey/create) it shows a JS error:
```Uncaught ReferenceError: indiciaData is not defined```

**Comment by johnvanbreda** [comment]
I'm not seeing that error on the page for creating a survey dataset - is that the page you had the error on and were there any other errors?

**Comment by kazlauskis** [comment]
Yes, it is on multiple pages. It could be my browser specific, I am using Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

Here is the full list of errors from visiting the survey datasets list page:
<img width="708" alt="screen shot 2018-04-22 at 12 10 17" src="https://user-images.githubusercontent.com/7383162/39094386-66dd449e-4626-11e8-930e-a726a8735719.png">

**Comment by johnvanbreda** [comment]
Fixed. Since move to https, $base_url was still pointing to http in the helper_config.php file.
