### ISSUE TITLE
Broken exporting or importing of a survey

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#295]
Exporting or importing a survey through website interface doesn't do anything, console error:
```GET https://warehouse1.indicia.org.uk/index.php/survey_structure_export 500 (Internal Server Error)```

From logs:
```Uncaught Kohana_Database_Exception: There was an SQL error: ERROR: column "survey_structure_export" does not exist ```

**Comment by johnvanbreda** [comment]
Can you describe the steps used to recreate this please? It didn't happen when I tried on a local warehouse.

**Comment by kazlauskis** [comment]
This could be linked to #294 

The steps:
1. Open the surveys list page: https://warehouse1.indicia.org.uk/index.php/survey
2. Click `New survey dataset`
3. Click `Import & export` tab

<img width="557" alt="screen shot 2018-04-22 at 12 15 12" src="https://user-images.githubusercontent.com/7383162/39094415-d74c99fa-4626-11e8-9b6f-29acecffb705.png">

**Comment by JimBacon** [comment]
The `Import & export` tab should not be shown when creating a new survey. There is no survey in existence at that point to export from or to import in to. The survey_structure_export controller expects to be able to obtain a survey ID from the url and this is not present.

In the [`survey_structure_export_extend_ui()`](https://github.com/Indicia-Team/warehouse/blob/master/modules/survey_structure_export/plugins/survey_structure_export.php#L3) function, a setting, `allowForNew` is set false. This sounds like it could be there to do what is needed and suppress the tab when creating a new survey. The same setting is used in several modules.

The problem appears to be in the [`extend_tabs()`](https://github.com/Indicia-Team/warehouse/blob/master/application/libraries/MY_View.php#L149) function where a comment indicates the code is going to skip tabs disallowed for new but the subsequent line does something else.

Seems to me we might need to insert a clause
```php
      if (isset($extend['allowForNew']) && $extend['allowForNew'] === FALSE {
        continue;
      }
```
