### ISSUE TITLE
Deleting an attribute

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#296]
I have deleted an occurrence attribute, but it still shows up in my survey and I can access it directly by its ID. Does it mean I haven't deleted it yet, or is it expected behaviour? Thanks!

For example, a deleted attr:
https://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/723

**Comment by johnvanbreda** [comment]
The attribute was mark deleted in the database, but using a saved link still shows the edit page even though the attribute did nothing. I've fixed this in the develop branch.

**Comment by kazlauskis** [comment]
Ah, thanks.
