### ISSUE TITLE
Release v1.60.0 broken CSS/images

### ISSUE THREAD

**Issue by Sebastian-Roth** [Indicia-Team/warehouse#298]
Is there a good reason behind linking the media submodule to commit [ceb4345](https://github.com/Indicia-Team/media/tree/ceb4345fa2c1504e057db1bf3ec773b0ec0eb1a2) (feature-bootstrap branch) in [release v1.60.0](https://github.com/Indicia-Team/warehouse/releases/tag/v1.60.0)? It is missing important files like site.css, menus.css and renamed `indicia_logo.png` to `indicia-logo.png` which also breaks with the code.

You can still logon to warehouse and it's able to receive posted data as far as I have tested but the interface is pretty basic and I am pretty sure this is not what people being new expect to see in a released version.

**Comment by JimBacon** [comment]
That would be a mistake. The feature-bootstrap branch of media and client_helpers submodules are just for the forthcoming warehouse version 2 which is currently in the warehouse develop branch.

**Comment by Sebastian-Roth** [comment]
Thanks for your answer! Seems like the new release [v1.60.1](https://github.com/Indicia-Team/warehouse/commit/4ec50544a74fc4d9489f0fde90fa6bd8048781ee) is still pointing to the media feature-bootstrap branch.

Can we inform @johnvanbreda about this?

**Comment by johnvanbreda** [comment]
Hi @Sebastian-Roth, thanks for pointing this out. The feature-bootstrap branches are in development ready for V2 of the warehouse and I'd accidentally committed them. I've released 1.60.2 which fixes this.
