### ISSUE TITLE
Support for newer PostgreSQL versions

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/warehouse#301]
In particular - test warehouse on Pg 10+

**Comment by BirenRathod** [comment]
PostgreSQL 10 has deployed on dev warehouse. 

In the log I found this error 
**There was an SQL error: ERROR:  set-returning functions are not allowed in CASE**
LINE 40:     then length((regexp_matches(searchterm, replace('jay', '...
                          ^
HINT:  You might be able to move the set-returning function into a LATERAL FROM item. - select   cts.taxa_taxon_list_id,
  cts.searchterm,
  ts_headline('simple', quote_literal(quote_literal(original)), to_tsquery('simple', 'jay:*')) as highlighted,
  cts.original as taxon,
  cts.authority,
  cts.language_iso,
  cts.preferred_taxon,
  cts.preferred_authority,
  cts.default_common_name,
  cts.taxon_group,
  cts.preferred,
  cts.preferred_taxa_taxon_list_id,
  cts.taxon_meaning_id,
  cts.external_key,
  cts.taxon_group_id,
  cts.parent_id,
  cts.identification_difficulty,
  cts.id_diff_verification_rule_id,
  cts.taxon_rank_sort_order

from cache_taxon_searchterms cts
where (cts.language_iso<>'lat' or preferred=true)
AND cts.name_type<>'A'
/* filter for the input search term */
AND ((cts.simplified=false and to_tsvector('simple', quote_literal(quote_literal(original))) @@ to_tsquery('simple', 'jay:*')))
/* end search term */
/* Context filter */
and cts.taxon_list_id in (15)
/* End context filter */
order by
-- abbreviation hits come first if enabled
cts.name_type='A' DESC,
-- prefer matches in correct epithet order
searchterm ilike '%' || replace('jay', ' ', '%') || '%' DESC,
-- prefer matches with searched phrase near start of term, by discarding the characters from the search term onwards and counting the rest
length(regexp_replace(searchterm, replace('jay', ' ', '.*') || '.*', '','i')),
-- prefer matches where the full search term is close together, by counting the characters in the area covered by the search term
case
  when searchterm ilike '%' || replace('jay', ' ', '%') || '%'
    then length((regexp_matches(searchterm, replace('jay', ' ', '.*'), 'i'))[1])
  else 9999 end,
cts.preferred desc,
-- finally alpha sort
taxon,
authority
limit 21; for language en_GB

I found this solution : 
https://tapoueh.org/blog/2017/10/set-returning-functions-and-postgresql-10/
