### ISSUE TITLE
Dev warehouse - Can't create Sample Attribute

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#307]
Saving Sample Attributes does not work in Dev Warehouse.
Error looks like it might be related to the new way attributes are linked together? (although I hadn't thought sample attributes were involved in the new code)

Error is this

15:25:32 debug array ( 
'sample_attribute:general' => 'The derived_from_taxa_taxon_list_attribute_id property does not exist in the Sample_Attribute_Model class.', 
)

**Comment by andrewvanbreda** [comment]
Still not working on BRC Dev Warehouse. Same error log as before.

**Comment by johnvanbreda** [comment]
Git pulled on that server - now fixed. I'd thought you wanted the DGfM server.

**Comment by andrewvanbreda** [comment]
Working now
