### ISSUE TITLE
Failure running on ubuntu 18.04 / php 7.2

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#310]
When installing warehouse version 1.60.2 on ubuntu 18.04 which comes with php7.2 i got the following error accessing data from the data service ore the warehouse fronted:

```
cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:http://localhost/indicia/index.php/services/data/location
Server response
{"error":"general_errors.count(): Parameter must be an array or an object that implements Countable","code":2,"file":"\/var\/www\/html\/indicia\/modules\/indicia_svc_data\/controllers\/services\/data.php","line":789,"trace":[]}
```

If I comment out the logger call in line 789 it seems to work.

**Comment by johnvanbreda** [comment]
Warehouse version 1.x (master branch) doesn't support PHP 7.2 without modification, but warehouse version 2.x (develop branch) does. The commits which cover compatibility for PHP 7.2 are:
d11bc3627f469a278a5e8ce4135e7b672f67f9d7
1812af4107b4220c03a9525471d6068d4f660cf7

If you want to try warehouse 2.x, you need to grab the develop branch of the main code, then the feature-bootstrap branch for both the client_helpers and media folders. v2 also supports PostgreSQL 10.x.

**Comment by dve** [comment]
Is it possible to backport these patches, or will it break compatibility with older php version?

Is the 2.x branch ready for production? Is there an overview of what changes form 1 to 2?

**Comment by johnvanbreda** [comment]
You could try backporting them - there are not very many changes so I don't think it would be hard. v2 is in production on a couple of warehouses now and passes our unit tests, though I would still recommend upgrading a test warehouse first before upgrading your live data. The changes are summarised in https://github.com/Indicia-Team/warehouse/blob/develop/CHANGELOG.md.
