### ISSUE TITLE
Indicia v2.6 setup php error

### ISSUE THREAD

**Issue by paul-gilbertson** [Indicia-Team/warehouse#315]
Indicia v2.6 linked from the Indicia downloads page has the following error when trying to set up.

`Warning: include(/var/www/html/modules/indicia_setup/libraries/Zend_Controller_Request_Http.php): failed to open stream: No such file or directory in /var/www/html/initialise.php on line 35`

**Comment by johnvanbreda** [comment]
Missing file re-instated in https://github.com/Indicia-Team/warehouse/releases/tag/v2.6.2.

I had thought this would be picked up by the automated testing, but it appears that the automated testing uses a custom config file to kick things off and this particular bit of code is only called when creation of the config.php file is required.
