### ISSUE TITLE
Database configuration page fails silently

### ISSUE THREAD

**Issue by paul-gilbertson** [Indicia-Team/warehouse#317]
Postgres database set up instructions miss two GRANT statements:

```
GRANT ALL PRIVILEGES ON ALL TABLES TO indicia_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES TO indicia_user;
```

this causes the database connection set up page to silently fail.

**Comment by johnvanbreda** [comment]
@paul-gilbertson this shouldn't be necessary if the following statement is run as per the instructions:
```sql
GRANT ALL PRIVILEGES ON DATABASE indicia TO indicia_user;
```
Did you successfully run this statement?

**Comment by paul-gilbertson** [comment]
Yes, and the above statements are still needed on PostgreSQL 10 under Ubuntu 18.04

**Comment by johnvanbreda** [comment]
Hi @paul-gilbertson. This has to be the following for Pg 9 compatibility:
```
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO indicia_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO indicia_user;
```

As this failure doesn't happen in my test setup, nor on Travis CI (which covers PG 10) I can't be sure this works, so if you get a chance to confirm it I'd appreciate it. Also do you have anything in the application/logs folder that would explain the exact failure?

**Comment by paul-gilbertson** [comment]
I can confirm this works.
