### ISSUE TITLE
Location linked sample attributes limited to one

### ISSUE THREAD

**Issue by burkmarr** [Indicia-Team/warehouse#321]
If multiple sample attributes are linked to a location, when the remembered location is selected in the iForm, only one of the location linked sample attributes is returned. This is because a of LIMIT clause set on the SQL query here: https://github.com/Indicia-Team/warehouse/blob/develop/reports/library/sample_attribute_values/get_latest_values_for_site_and_user.xml

Removing the LIMIT clause fixes the problem on my localhost with no apparent ill effects. I wonder if it was there during testing? Is there any chance that this can be fixed soon on the Dev Warehouse? I'm very keen on using multiple location-linked attributes for a demonstration form I am building there to show the Spider Recording Scheme.

**Comment by johnvanbreda** [comment]
I agree the limit is incorrect. But there is intended to be a limit on the latest sample (not just the latest single value), so removing the limit will make it return all samples.
How about something like (not tested):
```sql
SELECT * FROM (SELECT #columns#
  FROM sample_attribute_values sav
    JOIN sample_attributes sa on sa.id = sav.sample_attribute_id
    LEFT JOIN cache_termlists_terms ctt on ctt.id=sav.int_value AND sa.data_type='L'
  WHERE sa.applies_to_location = true
  AND sav.sample_id=(select max(id) from samples where s.created_by_id='#created_by_id#' and s.location_id='#location_id#'
  ORDER BY s.created_on DESC
LIMIT 1) AS subtable
```

You can also change the location_id columns sql to "'#location_id#'".

**Comment by burkmarr** [comment]
I have problems here - if the new subselect has max(id) is the order by and limit required? I got equivalent SQL for these two versions of the subselect working in pgAdmin (by replacing #columns# with ctt.*, and #created_by_id# and #location_id# with suitable values), but cannot get either to work in the indicia code. I'm not sure how to work out what is going wrong:

```sql
SELECT * FROM (SELECT #columns#
  FROM sample_attribute_values sav
    JOIN sample_attributes sa on sa.id = sav.sample_attribute_id
    LEFT JOIN cache_termlists_terms ctt on ctt.id=sav.int_value AND sa.data_type='L'
  WHERE sa.applies_to_location = true
  AND sav.sample_id = (select max(s.id) from samples s where s.created_by_id='#created_by_id#' and s.location_id='#location_id#')) AS subtable
```

```sql
  SELECT * FROM (SELECT #columns#
  FROM sample_attribute_values sav
    JOIN sample_attributes sa on sa.id = sav.sample_attribute_id
    LEFT JOIN cache_termlists_terms ctt on ctt.id=sav.int_value AND sa.data_type='L'
  WHERE sa.applies_to_location = true
  AND sav.sample_id = (select s.id from samples s where s.created_by_id='#created_by_id#' and s.location_id='#location_id#'
  ORDER BY s.created_on DESC
  LIMIT 1)) AS subtable
```

**Comment by johnvanbreda** [comment]
@burkmarr Here's a version of the query from the report which I think works:
```sql
SELECT * FROM (
    SELECT #columns#
    FROM sample_attribute_values sav
      JOIN sample_attributes sa on sa.id = sav.sample_attribute_id
      LEFT JOIN cache_termlists_terms ctt on ctt.id=sav.int_value AND sa.data_type='L'
    WHERE sa.applies_to_location = true
    AND sav.sample_id=(SELECT max(id) FROM samples WHERE created_by_id=#created_by_id# AND location_id=#location_id#)
  ) AS subtable
```

Also remember to change the location_id column definition since we no longer join to samples:
```xml
<column name='location_id' display='Location Id' sql='#location_id#' datatype='lookup' />
```

**Comment by burkmarr** [comment]
It was the change to the column definition that I didn't understand. With that in all three versions of the SQL work! Shall I commit the change to develop branch or some other workflow?

**Comment by johnvanbreda** [comment]
Yes please commit to develop.

**Comment by burkmarr** [comment]
Hi John. It's already done in commit cd46dea.
