### ISSUE TITLE
Make it easier to run dev and test servers which don't generate emails.

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/warehouse#323]
Running Indicia test and dev servers have 2 potential hazards in relation to emails:
1. If the server tries to generate a notification email of some kind and the test/dev environment is not set up to support mailing from PHP, then the scheduled tasks falls over. Therefore other background tasks fail to run.
2. If the server does have email configured correctly and you use a copy of live data, then you are at risk of generating incorrect spam emails. 

A setting in application/config/email.php to disable all attempts to send out emails would be very useful with documentation in the installation guide.

**Comment by burkmarr** [comment]
@johnvanbreda do you mean a setting in application/config/config.php?

**Comment by johnvanbreda** [comment]
Email.php is similar to config.php but specific to email settings, so seems like a more logical place? I don't have  strong opinion though.

**Comment by burkmarr** [comment]
There's not currently an email.php in the Warehouse. If I add one, will it be picked up - is it a Kohana thing?

**Comment by burkmarr** [comment]
Okay I've seen one on the live site now and I think from code that the answer is yes - it's a Kohana thing and if it's there it gets picked up.

**Comment by johnvanbreda** [comment]
Correct.

**Comment by burkmarr** [comment]
Pull request: https://github.com/Indicia-Team/warehouse/pull/324
