### ISSUE TITLE
Cannot use CSV upload on locations (eBMS transects)

### ISSUE THREAD

**Issue by burkmarr** [Indicia-Team/warehouse#344]
Hi @johnvanbreda. We need to upload a whole bunch of Spanish transects and transect sections into the Warehouse for eBMS/ABLE.

I have been unable to get the CSV upload of transect centroids to work. Originally I planned to workaround that by using the spatial (shapefile) upload for the transects, but I need to record the custom attributes 'No. of sections' and 'Country' which I should be able to do with CSV upload but which I don't think can be done with the shapefile upload.

Here's some test cases in a CSV:

![image](https://user-images.githubusercontent.com/9275178/70346392-27128280-1856-11ea-9905-cd44a5ac5c4d.png)

This is what I'm putting into the first part fo the CSV upload:

![import1](https://user-images.githubusercontent.com/9275178/70346470-4c06f580-1856-11ea-8bb8-b229e6206151.JPG)

As you can see, I'm specifying a single SRS for the whole file.

But after mapping the fields I want, the second part looks like this:

![import2](https://user-images.githubusercontent.com/9275178/70346559-81abde80-1856-11ea-90ec-dfd2c85b7991.JPG)

As you can see, I can't the file unless I map the 'Centroid sref' field. I find this confusing since I'm already mapping the 'Centroid geom' field. I wondred if 'Centroid sref' actually meant 'Centroid srs' so I mapped it to a field in my file which as the EPSG number. 

But the upload fails and the reason given in the CSV that specifies problems is:

```location:general: The spatial reference system epsgò‰±¦ is not recognised.```

I've tried all sorts of things including specifying lat/lng and lng/lat pairs to 'Centroid sref', but I just can't get it to work.

Am I doing something wrong or is this, as I suspect, a bug in the software?

Also tagging: @andrewvanbreda @Gary-van-Breda  and @DavidRoy

**Comment by andrewvanbreda** [comment]
54.58383N 7.14088W

Hi @burkmarr,

Keep in mind am just quickly looking at this for 10 mins on a saturday morning without have any other info about what you are attempting to do other than what you have written here.

I can confirm something weird is going on on my own machine, not even something simple like this  works, gives same warning you get.

iCode,iCentroid,iSref,iCountry
123,43.33089196235819N 8.41148167026404W,4326,Spain

Also I noticed if I don't specify a general spatial reference system for every row, it was not asking me to map that column.

The Centroid Sref field definetely should be specified. I don't think it can be written in the "Point(" format you have in your file though, I think it needs to be something like "43.33089196235819N 8.41148167026404W" or maybe "-8.41148167026404, 43.33089196235819" can't remember the exact format it accepts off top of my head. 
(As I can't get it to work, I can't check)

I don't think you need to specify the geom field as it is just a point.

I think something has happened in the code that has broken the importer.
As I say, that is my quick assessment, so might be wrong about some of what I have said.

**Comment by burkmarr** [comment]
Thanks @andrewvanbreda - at least I know that it's not just me. I'll have a look at the code and see if I can work out what's going on.

**Comment by andrewvanbreda** [comment]
Hi @burkmarr. Alsi check recent commit historys on import_helper.php and importer.php. Am pretty sure this is recent.

**Comment by johnvanbreda** [comment]
@burkmarr just for clarity:
* centroid_sref should be a textual representation of the location centre, e.g. a lat long (54.123N 0.234W) or OSGB grid ref (SY1234). 
* centroid_sref_system should be either the SRID of the projection (4326 for GPS lat long) or a code representing the grid ref notation (OSGB). You can't use the SRID associated with OSGB unless the centroid_sref is an easting/northing.
* centroid_geom - will normally be autogenerated from the centroid_sref, so you don't need to specify this.
* boundary_geom - a WKT format polygon for the location boundary, in web mercator (3857) projection.

Note that it's common to set the centroid_sref_system for the whole file on the first tab of the importer.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda and @andrewvanbreda. I have not been able to get to the bottom of this, but in the course of investigating it today I have found a workaround that will enable me to upload the ABLE data.

From the first part of the CSV upload where an SRS to apply to the whole CSV is picked from the drop-down list, the actual values passed through on the post request are of the format 'EPSG....'. For some reason, which I don't understand, the code HTML encodes these and 'EPSG:4326', for example, becomes 'EPSG&#564326'.

This is the first puzzle - and I thought the root of the problem - because the HTML character sequence ```&#56``` encodes the number 8, not a colon. The code for a colon is ```&#58``` (https://www.w3.org/MarkUp/html-spec/html-spec_13.html). I'm very confused by this because this encoding appears in a few places in the codebase. For the location stuff, it's in the function ```getConvertedOptionValue``` on line 349 of https://github.com/Indicia-Team/warehouse/blob/master/application/models/location.php. However changing that doesn't fix the problem. Neither does specifying a non-encoded value of "EPSG:4326'. However, what I found _did_ work was simply specifying 4326.

Once I knew that, I was able to use a rather awkward workaround which is to use Chrome Dev Tools to change the value passed on to the next stage of the import from 'EPSG&#564326' to '4326'. So at least I can use that to load the eBMS transect data.

But clearly - from the dates code was last changed - the code has worked by passing encoded ESPG values in the past, so I don't know why this was necessary or or even why it works.

Something else I don't understand about the Location CSV upload is that it is clearly the intention that it should be possible, instead of specifying an SRS for the whole file, to specify in the next stage a column which contains an SRS for each record. But there's no suitable field available in the drop down list to map such a field to (hence my initial confusion about the ```centroid_sref``` field.

After identifying the workaround, I spent several hours trying to  understand the problem better with a view to fixing it, but the whole Kohana architecture is very alien to me and I couldn't even find a way to display PHP variables for debugging in some cases, so I've dropped it. I think it needs someone with more experience of the system to tackle this at this point in my learning.

**Comment by andrewvanbreda** [comment]
@burkmarr 
I do not have any support time to be able to work on this. However I have tried a couple of things for you. I was sure I never saw the EPSG word before in the list of systems, I was right, looking at the CEDaR site which is attached to the BRC live warehouse, their importer is running old code and the list does not include the "EPSG:" bit.
I did try and revert some of the import files to older versions on my machine without success. 
Giving that the problem is not occurring on a site attached to the live warehouse, I can only assume the issue is at the Drupal iForm end
![Systems](https://user-images.githubusercontent.com/2463614/70624035-43783b80-1c17-11ea-9c8c-22660704fd8d.png)
 end.

**Comment by burkmarr** [comment]
Hi @andrewvanbreda. I was running this through the Warehouse ORM and it's there on the live Warehouse (http://warehouse1.indicia.org.uk/index.php/location). John has fixed this now on develop branch and I have the workaround for the live Warehouse if I need to upload the eBMS stuff before it's updated. Thanks for you help.
