### ISSUE TITLE
Species list options not showing on occurrence importer

### ISSUE THREAD

**Issue by DavidRoy** [Indicia-Team/warehouse#345]
Am attempting to import some occurrences into devwarehouse via:
http://devwarehouse.indicia.org.uk/index.php/occurrence/importer/1?

The dropdown list for [Species list] is not being populated.

Found the same issue on the live warehouse:
http://warehouse1.indicia.org.uk/index.php/index.php/occurrence/importer/1?

This bug is holding up:
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/125

Importer screenshot:
![import settings](https://user-images.githubusercontent.com/2699478/78459867-17943080-76b4-11ea-8bf6-9f250c528d0f.png)

**Comment by johnvanbreda** [comment]
Now fixed - control IDs were incorrectly escaped.

**Comment by DavidRoy** [comment]
Re-opening.  Fixing the Species list issue has led to another issue.  The Survey drop down is now not available once Website is selected.  On both development and warehouse1.

![importer_bug](https://user-images.githubusercontent.com/2699478/78597261-1b0af180-7845-11ea-90ed-29d1b9c8e118.png)

**Comment by johnvanbreda** [comment]
@DavidRoy I'm not able to reproduce this on warehouse1 on Chrome, Edge or Mac Safari. What browser are you using?

**Comment by DavidRoy** [comment]
Chrome
Google Chrome is up to date
Version 80.0.3987.163 (Official Build) (64-bit)

Should I clear any caches?

**Comment by johnvanbreda** [comment]
Yes, it might be worth clearing the cache.

**Comment by DavidRoy** [comment]
I now get a different error.
Fatal error: Method View::__toString() must not throw an exception, caught Error: Call to undefined function hostsite_show_message() in D:\websites\warehouse\application\views\templates\template.php on line 0

Here is the import settings.  Screen 1
![import screen 1](https://user-images.githubusercontent.com/2699478/78647938-298ff200-78b3-11ea-94c3-5ba4fda8af35.png)

Second screen
![import screen 2](https://user-images.githubusercontent.com/2699478/78647959-3280c380-78b3-11ea-8313-989e350b8e8a.png)

And file being loaded (renamed as .txt to enable it to be attached to this issue
[VisitCounts 1973 v2020 04 04 - Copy.txt](https://github.com/Indicia-Team/warehouse/files/4442940/VisitCounts.1973.v2020.04.04.-.Copy.txt)

**Comment by johnvanbreda** [comment]
This should now be sorted. I didn't test your exact import though as I wasn't sure which external key the mapping is to.

**Comment by DavidRoy** [comment]
I'm still getting the same error message.  I'm working on http://devwarehouse.indicia.org.uk

**Comment by DavidRoy** [comment]
The external key is for occurrences

**Comment by johnvanbreda** [comment]
Sorry, I'd not upgraded the devwarehouse, just live. Now done and tested - it worked OK with 3 errors.

**Comment by DavidRoy** [comment]
Thanks, that worked!
