### ISSUE TITLE
Upgrading database on fresh installation fails

### ISSUE THREAD

**Issue by dgslos** [Indicia-Team/warehouse#348]
![image](https://user-images.githubusercontent.com/65173064/83899931-8a279800-a759-11ea-9e1f-a65c4195e717.png)

**Comment by dgslos** [comment]
Same issue as here? https://github.com/Indicia-Team/warehouse/issues/347

**Comment by simonrolph** [comment]
Looks like the same issue as I had, what's your set-up? OS? version of PHP etc. ?

**Comment by johnvanbreda** [comment]
There's a new version which fixes these issues - see https://github.com/Indicia-Team/warehouse/releases/tag/v4.0.8.
