### ISSUE TITLE
Error "The last_name property does not exist in the Person_Model class."

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#349]
When editing an occurrence in the warehouse I get an error:

```The last_name property does not exist in the Person_Model class.```

If I understand it correct, the problem is a naming mismatch between:

https://github.com/Indicia-Team/warehouse/blob/master/application/views/occurrence/occurrence_edit.php#L104

and

https://github.com/Indicia-Team/warehouse/blob/master/application/models/person.php#L44

The first uses `last_name` while the later uses `surname` like in the databse

**Comment by JimBacon** [comment]
Closing as merged with master now.
