### ISSUE TITLE
Can not create tow people without email address

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#359]
When creating people I can only create one without an email address. The second one violates the unique key constraint.

The problem seems, that the constraint only checks on not deleted entries, but not on empty string or null email addresses:

https://github.com/Indicia-Team/warehouse/blob/master/modules/indicia_setup/db/version_0_8_0/201202220849_unique_email.sql

**Comment by dve** [comment]
The correct index would be:

```sql
CREATE UNIQUE INDEX ix_unique_email_address ON people (email_address)  WHERE deleted='f' AND email_address !='' AND email_address is not null;
```

**Comment by johnvanbreda** [comment]
Thanks @dve - I've committed a fix to the develop branch.
