### ISSUE TITLE
Work queue error after saving multiple terms in Warehouse

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#365]
If I save a term in the Live Warehouse it is ok, but after about 5 or 6 saves to different terms in succession I start getting following error, and need to wait for the work_queue to clear and come back later for it to start working again

06:04:34 error #44: Exception during postSubmit in termlists_term model.. There was an SQL error: ERROR: duplicate key value violates unique constraint "ix_work_queue_unique_task" 
DETAIL: Key (task, COALESCE(entity, ''::character varying), COALESCE(record_id, 0), COALESCE(params::text, ''::text))=(task_cache_builder_attrs_sample, sample, 3120675, ) already exists. - -- insert if not already exists 
INSERT INTO work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
SELECT DISTINCT 'task_cache_builder_attrs_sample', 'sample', v.sample_id, 2, 60, now() 
FROM sample_attribute_values v 
LEFT JOIN work_queue q ON q.task='task_cache_builder_attrs_sample' 
AND q.entity='sample' AND q.record_id=v.sample_id AND q.params IS NULL 
WHERE v.sample_attribute_id IN (1054,1542) 
AND v.int_value IN (13582); at line 352 in file D:\websites\warehouse\system\libraries\drivers\Database\Pgsql.php

**Comment by johnvanbreda** [comment]
Fixed in develop branch. As a workaround If you wait about 15 minutes normally it should allow saving again.
