### ISSUE TITLE
Survey CSV import does not include custom attributes

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#372]
Currently, when importing a list of surveys from a csv file, it is a single stage process which requires the csv file to contain a column to identify the website of each new survey. Because the website is not known a priori, it is not possible to map csv columns to custom survey attributes.

In order to be able to import custom attributes we need a two stage process as, for example, when importing samples. If a website is specified in the first stage as applying to all records then, in the second stage, it is possible to offer a mapping of csv column to custom survey attribute.

This is required to support the GLiTRS project but is of general usefulness should another project need to import many surveys.

**Comment by johnvanbreda** [comment]
You will need to override fixedValuesForm() in the survey model class to do this.

**Comment by JimBacon** [comment]
I just did that and magic happened :-)
