### ISSUE TITLE
Vague date type_code values undocumented

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#373]
The `samples:date_type` database field is currently described as "Vague date type code." without there being any detail on the value and meaning of the code. 

Lucky users might find http://www.recorder6.info/WebHelpR6V625/Topics/Vague_Dates_Stored.htm

We should describe the field better in the database and add something to the documentation.

**Comment by JimBacon** [comment]
This exposed a problem with the processing of `date_type`s, -Y, -C, and U. A null date_start was being converted to an empty string in validation, giving rise to an SQL exception when we attempted to insert that in a date field.

**Comment by johnvanbreda** [comment]
Some of the missing documentation is in the comments in application/tests/helpers/vague_dateTest.php. It may be worth incorporating the problems you found into the tests in this class.

**Comment by JimBacon** [comment]
Updated database description and also added information to https://indicia-docs.readthedocs.io/en/latest/developing/data-model/occurrences.html#samples

**Comment by JimBacon** [comment]
> This exposed a problem with the processing of `date_type` values, `-Y`, `-C`, and `U`. A null date_start was being converted to an empty string in validation, giving rise to an SQL exception when we attempted to insert that in a date field.

Fixed in https://github.com/Indicia-Team/warehouse/commit/df078f27d6a3581bfa0d2adaae51aa211765cf49
