### ISSUE TITLE
Unable to set vague-date custom attributes

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#382]
You can create custom attributes with type of vague date. However, you can never enter or edit such attributes via the warehouse website as the date picker control used does not have the 'allowVagueDates' option set.

**Comment by JimBacon** [comment]
Also, location attributes of type lookup are incorrectly displayed with the date picker control.

**Comment by JimBacon** [comment]
And vague dates attributes of taxa and locations are not regenerated for editing correctly. A value of 01/01/1970 is shown instead.

**Comment by johnvanbreda** [comment]
Regarding the original issue, the following line of code is supposed to automate setting allowVagueDates to true for existing records with vague dates: https://github.com/Indicia-Team/client_helpers/blob/fa4c3bdfcb3fa8e6fa15b2461999074329f2b634/data_entry_helper.php#L862

**Comment by JimBacon** [comment]
Thanks for comment. The original issue included that vague dates were not enabled for new records. I didn't word it too clearly though.

**Comment by JimBacon** [comment]
Also found vague dates for a winter season-in-year were not displayed correctly, mentioned in #150
