### ISSUE TITLE
Autocomplete not working for (parent) taxon

### ISSUE THREAD

**Issue by dgslos** [Indicia-Team/warehouse#389]
Hi,

I'm using a fresh indicia warehouse v6.0.0. installation, but when I want to add for example a parent taxon when adding a new taxon in the taxon list, nothing is showing up in the autocomplete field. I have to say I'm using the workbench in xampp and with http and not https. I have problems with the certificate. What could cause the autocomplete not working? I'm not getting errors...
Also in the drupal form, the autocomplete for taxa is not showing any taxa.

**Comment by johnvanbreda** [comment]
@dgslos can I check you've got a client_helpers folder and a media folder in the warehouse installation, both of which contain code? Github auto-generates a zip file of the source code for each release which doesn't include these sub-modules, so the installation is incomplete. There is a zip of the full install at https://github.com/Indicia-Team/warehouse/releases/tag/v6.2.0.

Have you actually managed to add some taxa to your warehouse installation? The fresh installation won't have any until you add some. 

Also after adding taxa, check that you have run the background scheduled tasks - see https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/scheduled-tasks.html.

**Comment by dgslos** [comment]
Thanks John! It were the scheduled tasks :)
