### ISSUE TITLE
Rest API locations endpoint not found

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#407]
Trying to access the index.php/services/rest/locations endpoint returns a 404 Not Found error

**Comment by johnvanbreda** [comment]
Are you sure it does not 401 unauthorized? That's what I'm seeing (which is correct behaviour). If on a local warehouse, check you have the rest_api module installed in application/config/config.php.

**Comment by JimBacon** [comment]
Quite sure. The method is missing from the code. I'll raise a pull request in a second for you to take a look at.

**Comment by johnvanbreda** [comment]
Agreed - I've commented on the review.
