### ISSUE TITLE
No file_box thumbnails when media subtype in options

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#415]
**Background**

When using a data_entry_helper::file_box for uploading media there is a subType option. The description for this is "The name of the image sub-type to limit the file box to e.g. Image:Local:Sketch"

There are also comments in the code as follows:

- If a subType option is supplied, it means we only want to load a particular media type, not just any old media associated with the sample.
- This option is supplied as text by the user. So go and look up the ID to use in code. 
- This allows there to be multiple photo controls, each saving its own type of image. This can keep the photos from each control independent of each other.

The ID comes from a hierarchical termlist of media types. The [first level](https://warehouse1.indicia.org.uk/index.php/termlist/edit/257?tab=terms) includes e.g. Image, Video, Audio. Each of these has a second level e.g.for  [Image](https://warehouse1.indicia.org.uk/index.php/termlists_term/edit/3741) containing terms like Image:Local, Image:Flickr, Image:iNaturalist. A convention of starting a child term with its parent term and a colon is apparent. This termlists_terms_id is stored in the `<model>_media:media_type_id` field of the database.

**Recreating the issue**

Four terms were added to a child list of Image:Local, with the intention of distinguishing 4 types of sample photo taken in the direction of the four cardinal points of the compass, e.g. Image:Local:North.

Four [sample photo] controls were added to a prebuilt form of type dynamic_sample_occurrence. Each was configured with options to associate it with a different image type. E.g.
```
[sample photo]
@label=South
@id=site-south
@maxFileCount=1
@tabDiv=tab-sitephotos
@subType=Image:Local:South
```
A photo was then uploaded to the control and saved. The following problems were observed.

1. There was no thumbnail of the image displayed in the form after uploading, just a file icon.
2. On editing the record, the word 'undefined' appears where the icon was previously.

**Additional findings**

Both errors arrive from the javascript in jquery.uploader.js looking for a template with a name like `file_box_uploaded_image:local:northTemplate`, which does not exist, instead of `file_box_uploaded_imageTemplate`

This arises from the list of fileTypes provided to the javascript by data_entry_helpers::file_box when a subType option is declared.

**Comment by JimBacon** [comment]
Hi @andrewvanbreda. This issue relates to some [code you committed](https://github.com/Indicia-Team/client_helpers/commit/0c31aa19f5a6bfe50f6d39c97eecb1fb35422bef#) in 2014.

In the commit message you say "This is currently useful for the seasearch project where we would want to keep sketches and photos separate." 

Can you recall if this feature is in use, for SeaSearch or anywhere else? I observe that the list of media types does not include Image:Local:Sketch which is what you were proposing to have.

I have a proposed fix in https://github.com/Indicia-Team/client_helpers/commit/68dfb6156e0c9fd80855d98247322c7a955d1749. This fixes the problem that I observe but I am wondering if it will break any existing sites that might somehow be using this feature in a way I haven't considered.

**Comment by andrewvanbreda** [comment]
Hi @JimBacon ,
I did the form coding for that, but John was in charge of the project management. I know initially they changed their mind about using the form, but I will check with John.
I can't think of any other projects that actually use the subtype.

Hi @johnvanbreda, was the Seasearch form ever used? I don't think it was, was it?

**Comment by johnvanbreda** [comment]
@andrewvanbreda @JimBacon the Seasearch form was never used in anger, so I would expect it to need revision before it is used again. So any changes should be fine from my perspective.

**Comment by JimBacon** [comment]
Fixed in https://github.com/Indicia-Team/client_helpers/commit/f58f86c24f18a5d4e591d88908ab3d4c4b004b48 but see discussion at https://github.com/BiologicalRecordsCentre/ABLE/issues/396#issuecomment-1027754951 regarding alternative implementations.
