### ISSUE TITLE
CSV upload not accepting 1/0 for boolean fields.

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#427]
In Indicia <= v6, CSV files could use 1/0 for representing boolean values.
This is no longer the case in v7.2-dev
It might be possible, with correct quotation, to ensure they are seen as string values rather than int, but I haven't succeeded yet.

**Comment by johnvanbreda** [comment]
@JimBacon does this relate to the switch to using PHPSpreadsheet for CSV file parsing?

**Comment by JimBacon** [comment]
Yes, that must be the case. I observe PHPSpreadsheet reads 1 and "1" from a CSV file as an integer type but PostGres only accepts a string into a boolean field. I can ensure boolean inputs are cast to string.
