### ISSUE TITLE
Warehouse functions not using correct volatility categories.

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/warehouse#44]
Forked from #42. Functions should be marked with the correct volatility category to allow the query planner to optimise more effectively - see http://www.postgresql.org/docs/9.4/static/xfunc-volatility.html. This has not been done on all functions (e.g. sref_system_to_srid which is volatile but could be marked immutable). 
Review and fix. The proposed changes are in the attached script.

[201511231408_function_volatility.txt](https://github.com/Indicia-Team/warehouse/files/41626/201511231408_function_volatility.txt)

**Comment by dve** [comment]
Line 212 reads from spatial_systems so the function is "only" stable. But the point is that content from spatial_systems likely will never change. I don't know what is best practise and clean here.
Line 315 re-introduces #42

the rest seems to be ok for me
