### ISSUE TITLE
Allow work_queue scheduled tasks to be run more frequently

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/warehouse#445]
Catch up of background tasks after large imports can be much quicker if just the work_queue part of the scheduled tasks is called more frequently. At the moment, it is only possible to control the tasks that scheduled_tasks runs when accessing from a browser via a URL, using a query parameter `tasks`. This doesn't work when calling from the command line via php.exe.

So, 2 tasks here.
1. Alter the scheduled tasks code to also look for parameters on the command line.
2. Set up the scheduled tasks on the warehouse to run the work queue every 2 minutes.

**Comment by johnvanbreda** [comment]
@BirenRathod can you set up a copy of the existing scheduled tasks call in the Task Scheduler on warehouse 1, but make it run every 2 minutes, with additional parameters on the command line `tasks=work_queue max-priority=2` please.

**Comment by BirenRathod** [comment]
@johnvanbreda I have setup scheduled_task now for work queue.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod
