### ISSUE TITLE
cache_occurrences_nonfunctional::verifier not set when inserting

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#452]
When importing records which have been verified externally to Indicia, the `occurrence::verified_by_id` can be set but the `cache_occurrences_nonfunctional::verifier` is not.

In `modules/cache_builder/config/cache_builder.php`, the `$config['occurrences']['insert']['nonfunctional']` needs to be updated to be similar to `$config['occurrences']['update']['nonfunctional']`

When Indicia was just used for harvesting new records they would always be unverified initially. Now we are asking it to curate existing records, this change is needed.

**Comment by JimBacon** [comment]
The fix suggested above is probably wrong, or incomplete at any rate.
I think changes to occurrences result in immediate changes to the cache tables so the cache builder is not involved in the case of importing new or updated records.

**Comment by johnvanbreda** [comment]
@JimBacon the cache builder is actually responsible for the immediate updates to cache tables as well as any delayed updates so your proposed change is probably correct.

**Comment by JimBacon** [comment]
Great, thanks. In my head I was thinking cache builder = scheduled tasks.
