### ISSUE TITLE
Failing REST API calls to log erroneous submissions [400]

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#463]
One really useful improvement to the warehouse will be to print out a serialized request body to the logs if an error happens. We used to do that in the past when we were using the Drupal proxy module but now that the apps directly communicate with the warehouse it is sometimes hard to see what user requests fail. `POST` to `samples` would be the most important method to improve but `locations` and other model endpoints would benefit from it too.

**Comment by kazlauskis** [comment]
I have noticed that the logs from the warehouse are now much more detailed.

**Comment by JimBacon** [comment]
> I have noticed that the logs from the warehouse are now much more detailed.

It has been logging at debug level since migrating to the new infrastructure to help us locate problems. It is intended to return to less detailed logs in due course as they are eating disk space.
