### ISSUE TITLE
Does our elastic search have a locations index?

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#470]
Looking at the current[ REST endpoints](https://warehouse1.indicia.org.uk/index.php/services/rest), it doesn't look like it exists, so maybe it would be worth adding it. Please close the ticket if the below is the recommended solution.

Our use case is to filter `es-occurrences` based on[ pre-indexed shapes](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_pre_indexed_shape), e.g. county or some specific area. Looking at how some reports were implemented, it seems that filtering `es-occurrences` with `location.higher_geography.id` is what we can use too. Does that mean adding new locations to the warehouse automatically updates all occurrences' `location.higher_geography` fields? Does it work with non-public locations too?

**Comment by johnvanbreda** [comment]
@kazlauskis there is no locations index on Elasticsearch currently, though it could be added.

We have 2 types of locations in the system. Standardised locations that are useful for many projects such as countries, counties or other administrative areas are pre-indexed and their details stored in `location.higher_geography`. Adding a location to one of these layers does automatically update `location.higher_geography`. Other locations which are project specific or personal to a recorder are not pre-indexed so if you want to filter to the contained occurrences we do a geoshape query in Elasticsearch, providing the co-ordinates of the boundary.

**Comment by kazlauskis** [comment]
Thanks. Linking the standardised administrative areas to  `location.higher_geography` and for everything else, using geoshape filters sounds like a good approach. 

We can't find some administrative boundaries in the warehouse yet, but I'll create a separate ticket later. Closing now.
