### ISSUE TITLE
High cost, low priority tasks in workqueue not happening

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#480]
There are 11 task_indicia_svc_security_delete_user_account tasks currently in the work queue with priority 3 and cost 100 which are up to a week old.

For them to be carried out requires the average processor load to be <= 10%. (application/libraries/WorkQueue.php::findMaxCostPriority)

I guess the server is just too busy to ever perform them. Some additional logging would help to confirm this.

**Comment by johnvanbreda** [comment]
The server has been catching up with data cleaner tasks which would have affected performance - it now seems to be up to date so I'd give it another day to see if they get picked up. We could of course tweak the thresholds so they are more likely to get run.

**Comment by JimBacon** [comment]
3 days later, following the weekend, those low priority tasks have now completed.
