### ISSUE TITLE
New installation warehouse SQL errors relating to people / users

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/warehouse#488]
I have a new local installation running (almost) but getting errors on the People (index.php/person) and User (index.php/user) lists in addition to the scheduled tasks and diagnostics summaries (index.php/diagnostics). 

The log displays the SQL headed with an error along the lines of "**error: Missing i18n entry general_errors. There was an SQL error: ERROR:  relation "people" does not exist**" but i don't know how to solve a missing 'relation' or what might be causing it.

Each page displays a similar error along the lines of:

`cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:http://localhost/indicia/index.php/services/report/requestReport?report=library/system/scheduled_task_summary.xml
Server response
{"error":"There was an SQL error: ERROR: relation \"system\" does not exist\nLINE 4: from system s\n ^ - \n select s.name as \"name\",\nlast_scheduled_task_check as \"last_scheduled_task_check\"\n from system s\n where last_scheduled_task_check is not null\n ORDER BY s.name = 'Indicia' desc, s.name LIMIT 21","code":44,"file":"C:\\xampp\\htdocs\\indicia\\system\\libraries\\drivers\\Database\\Pgsql.php","line":368,"trace":[]}
There was an SQL error: ERROR: relation "system" does not exist LINE 4: from system s ^ - select s.name as "name", last_scheduled_task_check as "last_scheduled_task_check" from system s where last_scheduled_task_check is not null ORDER BY s.name = 'Indicia' desc, s.name LIMIT 21`

- curl is installed / enabled.
- $base_url is correct so far as i understand it (points to the indicia at localhost).
- The xml's being referenced do exist at the location being pointed to.

I'm running the warehouse on php 8.0 as earlier and later versions cause an assortment of php related errors. It is perhaps worth noting i have previously had this error when trying to deploy to a web server, i gave up on that assuming it was something to do with the server hence attempting a local install.

I'm hoping this is a simple omission on my part, advice appreciated.

**Comment by benj-d** [comment]
Cheers Jim i can see the tables exist. Could the PostgreSQL version be causing an issue?

I set the database up following the tutorial and the rest of the warehouse tables are working fine (term lists, registering websites and datasets etc.. it's specifically the above pages only which are failing)

**Comment by JimBacon** [comment]
Our live server is on PostgreSQL 11.1 and development server is 12.3. We do unit testing against version 13. I wouldn't have expected a backwards incompatibility though.

I'm wondering if the common factor relates to accessing data via reports and whether there is an issue with the indicia_reports_user configuration. The pages for people and users have a different appearance to others and the error you posted above is certainly calling the report service. The config of this user is somewhat optional and the docs may not be totally obvious about this. If you have configured a report user you also have to grant them database permissions.

You can check if you have configured a report user by looking in application/config/database.php. If you have a `$config['report']` array then make a note of the associated user name and run a query like 

```sql
SELECT grantee, privilege_type 
FROM information_schema.role_table_grants 
WHERE table_name = 'system'
and grantee = 'your-report-user-name'
```
This should return indicating that user has select permissions.

**Comment by benj-d** [comment]
*sigh* the kind of issue i love. I'd created the report user but completely failed to assign them _any_ permissions. Granted read only now it's all working as expected. Cheers Jim!
