### ISSUE TITLE
Web Mercator projection, EPSG:900913

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/warehouse#490]
Just an observation that the tip relating to correcting projection for PostgreSQL 13 remains true for PostgreSQL 15

"_Tip If installing PostgreSQL 13, it may come with an incorrect projection for the Web Mercator projection, EPSG:900913. This will result in map data being recorded in the wrong location. To fix this, run the following query:_"

**Comment by JimBacon** [comment]
There is a separate Git repo for the docs.
See https://github.com/Indicia-Team/indicia-docs/blob/master//administrating/warehouse/warehouse-installation.rst
Can you have a look and see if the website allows you to make or suggest changes there?
We'd appreciate any improvements to help keep it up to date.

Moving issue there.
