### ISSUE TITLE
Taxon Designations tab sytax error

### ISSUE THREAD

**Issue by jendrage** [Indicia-Team/warehouse#497]
Uncaught ParseError: syntax error, unexpected single-quoted string ";", expecting "," or ";" in file modules/taxon_designations/models/taxa_taxon_designation.php on line 43:

`public $lookup_against = gv_taxa_taxon_designations';
`

should be:

`public $lookup_against = 'gv_taxa_taxon_designations';`

**Comment by johnvanbreda** [comment]
Code fix now in the develop branch - thanks @jendrage
