### ISSUE TITLE
Enable REST GET of multiple entities by ID

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/warehouse#511]
Occasionally, a feature must fetch multiple entities, e.g. samples, locations, groups, etc., by their IDs. To do that, we currently do multiple`/locations/:id` GET queries, which isn't efficient and makes it harder to keep the whole operation "transactional" if any fail. It would be useful if one could specify all the matching entity IDs using the REST API in a single request, like `/locations?id=123,456,789`.

**Comment by johnvanbreda** [comment]
Is this still a requirement now that you have GET groups/{id}/locations?
